version: "3.2"

networks:
  rabbit:
  influx:

services:
###################
## Rabbit Server ##
###################
  # https://registry.hub.docker.com/_/rabbitmq/
  rabbit-server:
    image: rabbitmq:3.8
    networks:
      - rabbit 
    ports:
      - "5672:5672" # exposed to host because kiscap2amqp needs networkmode: host
    restart: unless-stopped

##################
## Eewids Stuff ##
##################
  eewids-parser:
    build: eewids-parser
    networks:
      - rabbit 
    tty: true
    stdin_open: true
    entrypoint:
      - python
      - ./eewids-parser.py
      - --rabbit_host
      - rabbit-server
    depends_on:
      - rabbit-server
    restart: unless-stopped

###################
## Visualization ##
###################
  telegraf:
    image: telegraf:1.14
    volumes:
      - ./etc/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - rabbit-server
      - influxdb
    networks:
      - influx
      - rabbit
    expose:
      - "8092/udp"
      - "8094"
      - "8125/udp"
    restart: unless-stopped

  influxdb:
    image: influxdb:1.8
    volumes:
      - ./data/influxdb:/var/lib/influxdb
    networks:
      - influx
    expose:
      - "8086"
    restart: unless-stopped

  # https://grafana.com/docs/grafana/latest/installation/docker/
  grafana:
    image: grafana/grafana:7.0.5
    volumes:
      - ./data/grafana:/var/lib/grafana
      - ./etc/grafana/grafana.ini:/etc/grafana/grafana.ini:ro
      - ./etc/grafana/provisioning:/etc/grafana/provisioning
      - ./etc/grafana/dashboards:/etc/grafana/dashboards
    depends_on:
      - influxdb
    networks:
      - influx
    ports:
      - "3000:3000"
    restart: unless-stopped

#############
## Plugins ##
#############
#  rogueap:
#    build: plugins/rogueAP/
#    networks:
#      - rabbit
#    volumes:
#      - type: bind
#        source: ./data/rogueAP
#        target: /lists
#    tty: true
#    stdin_open: true
#    depends_on:
#      - rabbit-server
#      - eewids-parser
#    entrypoint:
#      - python
#      - rogueap.py
#      - --train
#      - --info
#    restart: on-failure
#
#  logprint:
#    build: plugins/logprint
#    networks:
#      - rabbit
#    tty: true
#    stdin_open: true
#    depends_on:
#      - rabbit-server
#      - eewids-parser
#    restart: on-failure

